---
- name: list file contents 
  hosts: all
  tasks:
    - name: list file content
      command: |
              systemctl set-default multi-user.target
              systemctl isolate multi-user.target

